= Kubeadm

== centos

The purpose of this document is to proivide the steps to install CJE2 on Kubernetes, provisioned via https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/[Kubeadm] on https://centos.org/[centos]

The examples were tested using centos 7 provisioned from the centos iso image (CentOS-7-x86_64-DVD-1804). The infrasctructure was

* Virtual box hosted VMs
* Reverse Proxy load balancer = NGINX
* Certificates via Ingress record (L4)

# Installation

## Firewall and selinux
This applies to all servers

During testing both firewalld and selinux caused issues, make sure both are disabled as follows.

It is obviously a concern for some customers, we should also do some work subsequently to configure with the required settings rather than simply disabling.

### firewalld
To disable and stop
```bash
systemctl disable firewalld
systemctl stop firewalld
```
### selinux
```bash
vi /etc/sysconfig/selinux
```
set the line SELINUX to disabled
```bash
SELINUX=disabled
```
Restart the instances

_Although documentation suggests that you are able to disable using "setenforce 0", this was not successful during testing_

## Master

* run updates
```bash
sudo yum update -y
```
* install docker
```bash
sudo yum install -y docker
```

* start docker
```bash
sudo systemctl enable docker && sudo systemctl start docker
```
* add the repo
```bash
sudo bash -c 'cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF'
```

* install kubelet, kubeadm and kubectl

```bash
sudo yum install -y kubelet kubeadm kubectl
```

* enable and start kubelet

```bash
sudo systemctl enable kubelet && sudo systemctl start kubeletsudo systemctl enable kubelet && sudo systemctl start kubelet
```

* set ip tables config

```bash
sudo bash -c 'cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF'
```

* reload config

```bash
sudo sysctl --system
```

* turn off swap
```bash
sudo swapoff -a
```

* init
```bash
sudo kubeadm init --pod-network-cidr 10.244.0.0/16
```

You will see instructions for attaching additional nodes to the cluster, although this can be used as displayed, tokens are only valid for 24 hours so
depending on your time scales you will need to generate a token an a hash.

* Create the token
```bash
kubeadm token create
```

* Create the hash

```bash
openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
```


* Install dns (Flannel)
```bash
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
```
* copy config
```bash
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

## Nodes

* run updates
```bash
sudo yum update -y
```
* install docker
```bash
sudo yum install -y docker
```
* start docker
```bash
sudo systemctl enable docker && sudo systemctl start docker
```

* add repo
```bash
sudo bash -c 'cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF'
```

* Install kubelet kubeadm kubectl
```bash
sudo yum install -y kubelet kubeadm kubectl
```

* set ip tables config

```bash
sudo bash -c 'cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF'
```

* reload config

```bash
sudo sysctl --system
```

* turn off swap
```bash
sudo swapoff -a
```
See above for generating a token and a hash
```bash
sudo kubeadm join <address of master>:6443 --token <token> --discovery-token-ca-cert-hash <hash>
```

## Install Ingress Controller

kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml


kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/baremetal/service-nodeport.yaml

## Other points to note
We had issues running without certs, in tests we are now running with a Public cert installed at the ingress, without "valid certs" we expereinced crumb errors.

If running with NFS provisioner and the nfs server also running on centos, make sure you disable firewalld and selinux  on the
NFS server as well as installing the nfs utils on each node. The container is unable to mount the volume without this being available on the host.

```bash
yum -y install nfs-utils
```


## Reverse Proxy load balancer
Although we disabled selinux, for security firewalld was enabled, ensuring that both http and https protocols were allowed
```bash
firewall-cmd --zone=public --add-service=https
firewall-cmd --zone=public --add-service=https
```

NGINX Configuration was keps minimal with ingress-proxy.conf set as follows, host ip and Kubernetes port mapping are exampled and
need to be amended to suit your environment

https://github.com/cloudbees/kubernetes-platform-validation/blob/master/kubeadm/centos/ingress-proxy.conf[ingress-proxy.conf]