= Kubeadm

== centos

The purpose of this document is to proivide the steps to install CJE2 on Kubernetes, provisioned via https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/[Kubeadm] on https://centos.org/[centos]

The examples were tested using centos 7 provisioned from the centos iso image (CentOS-7-x86_64-DVD-1804). The infrasctructure was

* Virtual box hosted VMs
* Reverse Proxy load balancer = NGINX
* Certificates via Ingress record (L4)

# Installation

## Firewall and selinux
This applies to all servers

During testing bioth firewalld and selinux caused issues, make sure both are disabled as follows.

It is obviously a concerns for some customers so we should also do some work subsequently to configure with the required settings rather than simply disabling.

### firewalld
To disable and stop
```bash
systemctl disable firewalld
systemctl stop firewalld
```
### selinux
```bash
vi /etc/sysconfig/selinux
```
set the line SELINUX to disabled
```bash
SELINUX=disabled
```
Restart the instances

_Although documentation suggests that you are able to disable using "setenforce 0", this was not successful during testing_

## Master

* run updates
```bash
sudo yum update -y
```
* install docker
```bash
sudo yum install -y docker
```

* start docker
```bash
sudo systemctl enable docker && sudo systemctl start docker
```
* add the repo
```bash
sudo bash -c 'cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF'
```

* install kubelet, kubeadm and kubectl

```bash
sudo yum install -y kubelet kubeadm kubectl
```

* enable and start kubelet

```bash
sudo systemctl enable kubelet && sudo systemctl start kubeletsudo systemctl enable kubelet && sudo systemctl start kubelet
```

* set ip tables config

```bash
sudo bash -c 'cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF'
```

* reload config

```bash
sudo sysctl --system
```

* turn off swap
```bash
sudo swapoff -a
```

* init
```bash
sudo kubeadm init --pod-network-cidr 10.244.0.0/16
```

The following is returned

```bash
"kubeadm join <address of the clustert>:6443 --token <token> --discovery-token-ca-cert-hash <hash>"
```

* Note: a token is supplied however these expire, to create a new token and hash, this is needed for adding new workers

* Create the token
```bash
kubeadm token create
```

* Create the hash

[source,block]
----
openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
----

* Install dns (Flannel)
```bash
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
```
* copy config
```bash
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

## Nodes

* run updates
```bash
sudo yum update -y
```
* install docker
```bash
sudo yum install -y docker
```
* start docker
```bash
sudo systemctl enable docker && sudo systemctl start docker
```

* add repo
```bash
sudo bash -c 'cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF'
```

* Install kubelet kubeadm kubectl
```bash
sudo yum install -y kubelet kubeadm kubectl
```

* set ip tables config

```bash
sudo bash -c 'cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF'
```

* reload config

```bash
sudo sysctl --system
```

* turn off swap
```bash
sudo swapoff -a
```
See above for generating a token and a hash
```bash
sudo kubeadm join 192.168.1.163:6443 --token <token> --discovery-token-ca-cert-hash <hash>
```

## Install Ingress Controller

kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml


kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/baremetal/service-nodeport.yaml
